nelmio_alice:
    locale: 'fr_FR' # Default locale for the Faker Generator
    functions_blacklist:
        - 'current'
        - 'shuffle'
        - 'date'
        - 'time'
        - 'file'
        - 'md5'
        - 'sha1'
