lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'lolo1986' # required for token creation, usage of an environment variable is recommended
    token_ttl:        10800

    # token_extractors:
    #     # authorization_header:
    #     #     enabled: true
    #     #     prefix:  Bearer
    #     #     name:    Authorization
    #     cookie:
    #         enabled: true
    #         name:    TOTO

    
    # set_cookies:
    #     TOTO: 
    #         # lifetime: null 
    #         # samesite: none
    #         path: /
    #         # domain: null

